# Site settings

project:
    name: "PrioritizeRoutes"
    alt_name: "PrioritizeRoutes"
    tagline: The WebSocket server for Laravel
    author: "CupOfTea696"
    github: "https://github.com/CupOfTea696/PrioritizeRoutes/"
    package: "cupoftea/prioritize-routes"
navigation:
  - name: Documentation
    url: "docs"
    navigation:
      - name: Installation
        type: page
        url: "installation"
      - name: Usage
        type: page
        url: "usage"
url: "http://prioritize-routes.cupoftea.io"
twitter_username: CupOfTea696
github_username:  CupOfTea696

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'with_toc_data', 'html_toc', 'strikethrough', 'autolink', 'tables', 'footnotes', 'underline']
highlighter: pygments
pygments_options: ['startinline']
gems:
  - jekyll-assets
  - nokogiri
  - octopress-minify-html
assets:
  dirname: assets
  base_url: assets/
  cachebust: soft
  js_compressor: uglifier
  css_compressor: sass
  gzip: [ text/css, application/javascript ]
  sources:
    - _assets
